### ISSUE TITLE
please expose activity - feature request 

### ISSUE THREAD

**Issue by priestdo** [corbinlc/gnuroot#71]
Hi,

I would like to be able to launch back into a running GNUroot session. Currently to do that I must either pull down notifications and select the "Terminal Emulator, Terminal session is running" notification, or I  run the activity "com.gnuroot.debian/jackpal.androidterm.Remoteinterface"  which starts a 2nd terminal window which I then exit to get to my proot.   As the goal is to get back to the running GNUroot session without seeing or touching the phone, I currently take the 2nd approach, but it is cumbersome to have to then exit the window each time in order to get back to the original window

I would like to be able to run the activity "com.gnuroot.debian/jackpal.androidterm.Term" which is what logs show the notification bar is doing, so that I can go directly into the existing proot session.  But that activity is not exposed and so not available for me to bind to something.

Could you please allow us to launch that activity directly? I _think_ it was available in the past but I may be remembering when I ran linux from a chroot (in the dark pre-gnuroot past...).

Thanks,

-Greg

**Comment by priestdo** [comment]
2 additional things, 
1 - typo on my part, "Remoteinterface" should be "RemoteInterface"
2 - here is the console output when doing these things as non-root and sending the to an adb shell:

(0)[16:31]$ adb shell am start com.gnuroot.debian/jackpal.androidterm.Term
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.gnuroot.debian/jackpal.androidterm.Term }
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.gnuroot.debian/jackpal.androidterm.Term } from null (pid=19860, uid=2000) not exported from uid 10102
    at android.os.Parcel.readException(Parcel.java:1620)
    at android.os.Parcel.readException(Parcel.java:1573)
    at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2694)
    at com.android.commands.am.Am.runStart(Am.java:875)
    at com.android.commands.am.Am.onRun(Am.java:359)
    at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
    at com.android.commands.am.Am.main(Am.java:100)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)

and of course it does not launch, but

(0)[16:58]$ adb shell am start com.gnuroot.debian/jackpal.androidterm.RemoteInterface
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.gnuroot.debian/jackpal.androidterm.RemoteInterface }

Launches jackpal and starts a new window.  I can then exit that window and be dropped back into the proot.

-Greg

**Comment by ghost** [comment]
seconding this. when i background the app and then reopen it, the only way to get back to the terminal seems to be to either press the back button or open a new window and switch to the existing one
